### PR TITLE
Hacktoberfest Commit

### PR DESCRIPTION
**Pull request by pingrishabh**
Complete UI/UX Revamp

-Title Bar Removed

-Photo Added In CircleImageView

-Gradients Added

-Background Gradient Animation

-Card Border Added

-Text Border Added

-Birthday Cake Drawable Added

-From ND Inside Border Layout

### CODE REVIEW

**Review by Pritom14 — CHANGES_REQUESTED** [review]
you don't have to add all the files that was changed, only the layout files and the activity files and the gradle file if and only if you have added any other dependency

**Comment by pingrishabh** [comment]
I Forked and then added changes. It's okay. All you have to do is pull the
code. Or you can clone it using GitHub Desktop.

**Comment by Pritom14** [comment]
I know that you did all that , but what I am saying is that when you open the project in `Android Studio`, it makes some changes in some of the files such as `gradle` files without you knowing about it. So, next time when you send a PR , dont type `git add --all` , type `git status` you will get what all files are modified, the you enter `git add <address of the modified files which you changed intentionally>` like `layout` and `activity` files. In your case `gradle.xml` , `misc.xml` , `gradle-wrapper.properties` files are changed and they are not required in the PR, but `app/build.gradle` file was ok since you added a new `dependency`.

**Comment by pingrishabh** [comment]
Alright. I understood what you said. I'll definitely keep that in mind the
next time. Although, what about now? Are you going to accept the pull
request?

**Comment by Pritom14** [comment]
I am sorry but I am not the owner of the repository, I just reviewed it

**Comment by nnamdei** [comment]
thanks guys, really appreciate the input

**Pull request closed without merging**
